product_areas:
  APIs:
  - team-enterprise
  Alerts:
  - team-issues
  Crons:
  - team-crons
  Dashboards:
  - team-discover-and-dashboards
  Discover:
  - team-discover-and-dashboards
  Docs:
  - team-docs
  Footer:
  - team-issues
  Help:
  - team-support
  Issues:
  - team-issues
  Issues - Source Maps:
  - team-processing
  - team-web-sdks
  - team-mobile-sdks
  Issues - Suggested Fix:
  - team-telemetry-experience
  Org Relocation:
  - team-ospo
  Performance:
  - team-performance
  Profiling:
  - team-profiling
  Projects - Project Creation:
  - team-telemetry-experience
  Projects - Project Details:
  - team-issues
  Releases:
  - team-issues
  Replays:
  - team-replays
  SDKs - Mobile:
  - team-mobile-sdks
  SDKs - Native:
  - team-mobile-sdks
  - team-processing
  SDKs - Web Backend:
  - team-web-sdks
  SDKs - Web Frontend:
  - team-web-sdks
  Settings:
  - team-issues
  Settings - Auth:
  - team-enterprise
  Settings - Developer Settings:
  - team-enterprise
  Settings - General:
  - team-issues
  Settings - Integrations:
  - team-enterprise
  Settings - Members:
  - team-enterprise
  Settings - Projects:
  - team-enterprise
  Settings - Relay:
  - team-ingest
  Settings - Repositories:
  - team-enterprise
  Settings - Security & Privacy:
  - team-sentry-at-scale
  Settings - Spend Allocation:
  - team-enterprise
  Settings - Spike Protection:
  - team-enterprise
  Settings - Subscription:
  - team-revenue
  Settings - Teams:
  - team-enterprise
  Sign In:
  - team-enterprise
  Starfish:
  - team-starfish
  Starfish - API:
  - team-starfish
  Starfish - Database:
  - team-starfish
  Stats:
  - team-enterprise
  User Feedback:
  - team-issues
  What's New:
  - team-product
repos:
  arroyo: team-sns
  cdc: team-sns
  craft: team-ospo
  relay: team-ingest
  responses: team-ospo
  self-hosted: team-ospo
  sentry-android-gradle-plugin: team-mobile-sdks
  sentry-cocoa: team-mobile-sdks
  sentry-dart: team-mobile-sdks
  sentry-dart-plugin: team-mobile-sdks
  sentry-dotnet: team-mobile-sdks
  sentry-java: team-mobile-sdks
  sentry-javascript: team-web-sdks
  sentry-javascript-bundler-plugins: team-web-sdks
  sentry-laravel: team-web-sdks
  sentry-native: team-processing
  sentry-php: team-web-sdks
  sentry-python: team-web-sdks
  sentry-react-native: team-mobile-sdks
  sentry-ruby: team-web-sdks
  sentry-symfony: team-web-sdks
  sentry-unity: team-mobile-sdks
  sentry-wizard: team-web-sdks
  snuba: team-sns
  snuba-sdk: team-sns
  symbolic: team-processing
  symbolicator: team-processing
  wal2json: team-sns
teams:
  team-crons:
    offices: null
    slack_channel: null
  team-discover-and-dashboards:
    offices: null
    slack_channel: null
  team-docs:
    offices: null
    slack_channel: null
  team-enterprise:
    offices: null
    slack_channel: null
  team-ingest:
    offices: null
    slack_channel: null
  team-issues:
    offices: null
    slack_channel: null
  team-mobile-sdks:
    offices: null
    slack_channel: null
  team-ospo:
    offices:
    - sea
    slack_channel: C04B27EECUB
  team-performance:
    offices: null
    slack_channel: null
  team-processing:
    offices: null
    slack_channel: null
  team-product:
    offices: null
    slack_channel: null
  team-profiling:
    offices: null
    slack_channel: null
  team-replays:
    offices: null
    slack_channel: null
  team-revenue:
    offices: null
    slack_channel: null
  team-sentry-at-scale:
    offices: null
    slack_channel: null
  team-sns:
    offices: null
    slack_channel: null
  team-starfish:
    offices: null
    slack_channel: null
  team-support:
    offices: null
    slack_channel: null
  team-telemetry-experience:
    offices: null
    slack_channel: null
  team-web-sdks:
    offices: null
    slack_channel: null
