product_areas:
  APIs:
  - team-enterprise
  Alerts:
  - team-issues
  Bug Report:
  - team-issues
  Crons:
  - team-crons
  DDM:
  - team-telemetry-experience
  Dashboards:
  - team-discover-and-dashboards
  Discover:
  - team-discover-and-dashboards
  Docs:
  - team-docs
  Footer:
  - team-issues
  Help:
  - team-support
  Issues:
  - team-issues
  Issues - Source Maps:
  - team-processing
  - team-web-frontend-sdks
  - team-mobile-sdks
  Issues - Suggested Fix:
  - team-telemetry-experience
  Org Relocation:
  - team-ospo
  Other:
  - team-ospo
  Performance:
  - team-performance
  Performance - Interactions:
  - team-performance
  Performance - Queries:
  - team-performance
  Performance - Web Vitals:
  - team-performance
  Profiling:
  - team-profiling
  Projects - Project Creation:
  - team-telemetry-experience
  Projects - Project Details:
  - team-issues
  Releases:
  - team-issues
  Replays:
  - team-replays
  SDKs - Mobile:
  - team-mobile-sdks
  SDKs - Native:
  - team-mobile-sdks
  - team-processing
  SDKs - Web Backend:
  - team-web-backend-sdks
  SDKs - Web Frontend:
  - team-web-frontend-sdks
  Settings:
  - team-issues
  Settings - Auth:
  - team-enterprise
  Settings - Developer Settings:
  - team-enterprise
  Settings - General:
  - team-issues
  Settings - Integrations:
  - team-integrations
  Settings - Members:
  - team-enterprise
  Settings - Projects:
  - team-enterprise
  Settings - Relay:
  - team-ingest
  Settings - Repositories:
  - team-enterprise
  Settings - Security & Privacy:
  - team-sentry-at-scale
  Settings - Spend Allocation:
  - team-enterprise
  Settings - Spike Protection:
  - team-enterprise
  Settings - Subscription:
  - team-revenue
  Settings - Teams:
  - team-enterprise
  Sign In:
  - team-enterprise
  Stats:
  - team-enterprise
  Unknown:
  - team-ospo
  User Feedback:
  - team-issues
  What's New:
  - team-product
repos:
  arroyo: team-sns
  cdc: team-sns
  craft: team-ospo
  relay: team-ingest
  responses: team-ospo
  self-hosted: team-ospo
  sentry-android-gradle-plugin: team-mobile-sdks
  sentry-cocoa: team-mobile-sdks
  sentry-dart: team-mobile-sdks
  sentry-dart-plugin: team-mobile-sdks
  sentry-dotnet: team-web-backend-sdks
  sentry-electron: team-web-frontend-sdks
  sentry-elixir: team-web-backend-sdks
  sentry-go: team-web-backend-sdks
  sentry-java: team-cross-platform-java
  sentry-javascript: team-web-frontend-sdks
  sentry-javascript-bundler-plugins: team-web-frontend-sdks
  sentry-laravel: team-web-backend-sdks
  sentry-native: team-cross-platform-native
  sentry-php: team-web-backend-sdks
  sentry-python: team-web-backend-sdks
  sentry-react-native: team-mobile-sdks
  sentry-ruby: team-web-backend-sdks
  sentry-symfony: team-web-backend-sdks
  sentry-unity: team-web-backend-sdks
  sentry-unreal: team-web-backend-sdks
  sentry-wizard: team-web-frontend-sdks
  snuba: team-sns
  snuba-sdk: team-sns
  symbolic: team-processing
  symbolicator: team-processing
  wal2json: team-sns
teams:
  team-crons:
    offices:
    - sfo
    slack_channel: C062HDG1MT7
  team-cross-platform-java:
    offices:
    - vie
    slack_channel: C0190510ABF
  team-cross-platform-native:
    offices:
    - vie
    slack_channel: C027HJCKP0V
  team-discover-and-dashboards:
    offices:
    - yyz
    slack_channel: C05F7G32M4Z
  team-docs:
    offices:
    - sea
    - sfo
    slack_channel: C05CR9FM4AE
  team-enterprise:
    offices:
    - sfo
    slack_channel: CSD1XPPQA
  team-ingest:
    offices:
    - vie
    slack_channel: C019637C760
  team-integrations:
    offices:
    - sfo
    slack_channel: CD4NYFD34
  team-issues:
    offices:
    - sfo
    slack_channel: C0549083GJJ
  team-mobile-sdks:
    offices:
    - vie
    slack_channel: C0190510ABF
  team-ospo:
    offices:
    - sea
    slack_channel: C04B27EECUB
  team-performance:
    offices:
    - yyz
    slack_channel: C04Q3BDL8MA
  team-processing:
    offices:
    - vie
    slack_channel: C05LK7YQRFE
  team-product:
    offices:
    - sfo
    slack_channel: C055Y9KB1AS
  team-profiling:
    offices:
    - sfo
    slack_channel: C02N5PB50JH
  team-replays:
    offices:
    - sfo
    slack_channel: C04B0K358QM
  team-revenue:
    offices:
    - sfo
    slack_channel: C018ZU6704S
  team-sentry-at-scale:
    offices:
    - sfo
    slack_channel: CSD1XPPQA
  team-sns:
    offices:
    - sfo
    slack_channel: C05M9TU0RRR
  team-support:
    offices:
    - sfo
    - yyz
    slack_channel: C02KHRNRZ1B
  team-telemetry-experience:
    offices:
    - vie
    slack_channel: C047YNXDDA7
  team-web-backend-sdks:
    offices:
    - vie
    slack_channel: C032NTYCA3B
  team-web-frontend-sdks:
    offices:
    - vie
    slack_channel: C031EJRRDS8
