product_areas:
  APIs:
  - team-ecosystem
  Alerts:
  - team-alerts-notifications
  Crons:
  - team-crons
  DDM:
  - team-telemetry-experience
  Dashboards:
  - team-dashboards
  Discover:
  - team-explore
  Docs:
  - team-docs
  Explore:
  - team-explore
  Explore - Logs:
  - team-ourlogs
  Footer:
  - team-issues
  GDX:
  - team-gdx
  Help:
  - team-support
  Ingestion and Filtering:
  - team-ingest
  Insights:
  - team-insights
  Issues:
  - team-issues
  Issues - Source Maps:
  - team-web-frontend-sdks
  - team-mobile-sdks
  Issues - Suggested Fix:
  - team-machine-learning
  Org Relocation:
  - team-dev-infra
  Other:
  - team-dev-infra
  Performance:
  - team-performance
  Processing:
  - team-ingest
  Profiling:
  - team-profiling
  Projects - Project Creation:
  - team-telemetry-experience
  Projects - Project Details:
  - team-issues
  Releases:
  - team-replays
  Replays:
  - team-replays
  SDKs - Mobile:
  - team-mobile-sdks
  SDKs - Native:
  - team-mobile-sdks
  SDKs - Web Backend:
  - team-web-backend-sdks
  SDKs - Web Frontend:
  - team-web-frontend-sdks
  Settings:
  - team-issues
  Settings - Auth:
  - team-foundations
  Settings - Developer Settings:
  - team-foundations
  Settings - General:
  - team-issues
  Settings - Integrations:
  - team-ecosystem
  Settings - Members:
  - team-foundations
  Settings - Projects:
  - team-foundations
  Settings - Relay:
  - team-ingest
  Settings - Repositories:
  - team-ecosystem
  Settings - Security & Privacy:
  - team-foundations
  Settings - Spend Allocation:
  - team-revenue
  Settings - Spike Protection:
  - team-revenue
  Settings - Subscription:
  - team-revenue
  Settings - Teams:
  - team-foundations
  Sign In:
  - team-foundations
  Stats:
  - team-revenue
  Unknown:
  - team-dev-infra
  User Feedback:
  - team-replays
  What's New:
  - team-product
repos:
  arroyo: team-sns
  cdc: team-sns
  craft: team-dev-infra
  relay: team-ingest
  responses: team-dev-infra
  self-hosted: team-dev-infra
  sentry-android-gradle-plugin: team-mobile-sdks
  sentry-cli: team-web-backend-sdks
  sentry-cocoa: team-mobile-sdks
  sentry-dart: team-mobile-sdks
  sentry-dart-plugin: team-mobile-sdks
  sentry-dotnet: team-gdx
  sentry-electron: team-web-frontend-sdks
  sentry-elixir: team-web-backend-sdks
  sentry-go: team-web-backend-sdks
  sentry-godot: team-gdx
  sentry-java: team-cross-platform-java
  sentry-javascript: team-web-frontend-sdks
  sentry-javascript-bundler-plugins: team-web-frontend-sdks
  sentry-laravel: team-web-backend-sdks
  sentry-native: team-cross-platform-native
  sentry-php: team-web-backend-sdks
  sentry-powershell: team-gdx
  sentry-python: team-web-backend-sdks
  sentry-react-native: team-mobile-sdks
  sentry-ruby: team-web-backend-sdks
  sentry-symfony: team-web-backend-sdks
  sentry-unity: team-gdx
  sentry-unreal: team-gdx
  sentry-wizard: team-web-frontend-sdks
  snuba: team-sns
  snuba-sdk: team-sns
  symbol-collector: team-gdx
  symbolic: team-ingest
  symbolicator: team-ingest
  wal2json: team-sns
teams:
  team-alerts-notifications:
    offices:
    - sfo
    slack_channel: C06J6HKFKLG
  team-crons:
    offices:
    - sfo
    slack_channel: C062HDG1MT7
  team-cross-platform-java:
    offices:
    - vie
    slack_channel: C0190510ABF
  team-cross-platform-native:
    offices:
    - vie
    slack_channel: C027HJCKP0V
  team-dashboards:
    offices:
    - yyz
    slack_channel: C026Y0SK34H
  team-dev-infra:
    offices:
    - sfo
    - sea
    slack_channel: C05816N2A2K
  team-docs:
    offices:
    - sea
    - sfo
    slack_channel: C05CR9FM4AE
  team-ecosystem:
    offices:
    - sfo
    slack_channel: C058EAWNF1P
  team-explore:
    offices:
    - yyz
    - sfo
    slack_channel: C026Y0SK34H
  team-foundations:
    offices:
    - sfo
    slack_channel: CSD1XPPQA
  team-gdx:
    offices:
    - vie
    slack_channel: C07QW5CGHN3
  team-ingest:
    offices:
    - vie
    slack_channel: C019637C760
  team-insights:
    offices:
    - yyz
    slack_channel: C026Y0SK34H
  team-integrations:
    offices:
    - sfo
    slack_channel: C058EAWNF1P
  team-issues:
    offices:
    - sfo
    - yyz
    slack_channel: C0549083GJJ
  team-machine-learning:
    offices:
    - sfo
    slack_channel: C064URR6RPT
  team-mobile-sdks:
    offices:
    - vie
    slack_channel: C0190510ABF
  team-ourlogs:
    offices:
    - yyz
    slack_channel: C0887GWU26M
  team-performance:
    offices:
    - yyz
    slack_channel: C026Y0SK34H
  team-product:
    offices:
    - sfo
    slack_channel: C055Y9KB1AS
  team-profiling:
    offices:
    - sfo
    slack_channel: C02N5PB50JH
  team-replays:
    offices:
    - yyz
    slack_channel: C04B0K358QM
  team-revenue:
    offices:
    - sfo
    slack_channel: C018ZU6704S
  team-sentry-at-scale:
    offices:
    - sfo
    slack_channel: CSD1XPPQA
  team-sns:
    offices:
    - sfo
    slack_channel: C05M9TU0RRR
  team-support:
    offices:
    - sfo
    - yyz
    slack_channel: C02KHRNRZ1B
  team-telemetry-experience:
    offices:
    - vie
    slack_channel: C047YNXDDA7
  team-web-backend-sdks:
    offices:
    - vie
    slack_channel: C032NTYCA3B
  team-web-frontend-sdks:
    offices:
    - vie
    slack_channel: C031EJRRDS8
