export enum SlackMessage {
  REQUIRED_CHECK = 'required-check',
  PLEASE_DEPLOY = 'please-deploy',
  GOCD_CUSTOM_JOB_RUN = 'gocd-custom-job-run',
  FEED_ENG_DEPLOY = 'feed-eng-deploy',
  FEED_DEV_INFRA_GOCD_DEPLOY = 'feed-dev-infra-gocd-deploy',
  FEED_ENGINGEERING_DEPLOY = 'feed-engineering-deploy',
  FEED_SNS_SAAS_DEPLOY = 'feed-sns-saas-deploy',
  FEED_SNS_ST_DEPLOY = 'feed-sns-st-deploy',
  FEED_INGEST_DEPLOY = 'feed-ingest-deploy',
  FEED_SDKS_DEPLOY = 'feed-sdk-deploy',
  FEED_SNS_SAAS_K8S = 'feed-sns-saas-k8s',
  FEED_SNS_S4S_K8S = 'feed-sns-st-k8s',
  DISCUSS_BACKEND_DEPLOY = 'discuss-backend-deploy',
  DISCUSS_SNS_DEPLOY = 'discuss-sns-deploy',
}
